# scripts/mine_gcc_keywords.py
"""Accumulate classified history, then propose Signal GCC keywords from it.

Run daily alongside the other build scripts:

    python scripts/mine_gcc_keywords.py --record     # append today's corpus
    python scripts/mine_gcc_keywords.py              # report proposals
    python scripts/mine_gcc_keywords.py --write      # ...and write the file

--record is the part that must run every day. The article cache holds one
slot and is overwritten on each scrape, so without a store the sample is
however many GCC stories ran today -- usually one, which is far too few for
lift to mean anything. The store is what turns a day into a corpus.

Nothing this script writes is live. Proposals land in
config/gcc_candidates.yaml with their evidence, for a person to promote into
app/analysis/signals.py by hand.
"""
import argparse
import logging
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv
load_dotenv()

from app.analysis.signals import classify_article
from app.intelligence.gcc_mining import (MIN_COOCCURRENCE, MIN_LIFT,
                                         MIN_SUPPORT, demotions, load_history,
                                         mine, record_day, record_path)
from app.scraper.store import get_articles, get_cache_date

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)

CANDIDATES = ROOT / 'config' / 'gcc_candidates.yaml'


def _write_candidates(candidates, stats, flagged):
    lines = [
        '# PROPOSED Signal GCC keywords -- NOT ACTIVE.',
        '#',
        '# Generated by scripts/mine_gcc_keywords.py. Nothing here is read by',
        '# the classifier. To adopt a term, move it into GCC_ENTITY or the',
        '# right GCC_ACTION facet in app/analysis/signals.py by hand.',
        '#',
        '# Every candidate below cleared both gates:',
        '#   lift          >= %.1f   (how much more it belongs to GCC stories',
        '#                            than to news in general)',
        '#   cooccurrence  >= %.2f   (share of its GCC appearances sitting',
        '#                            beside a weight-4 entity term -- the',
        '#                            test that it points AT a capability',
        '#                            centre rather than merely near one)',
        '#   support       >= %d      distinct confirmed GCC stories',
        '#',
        '# Weight is banded from lift. Weight 4 is never proposed: naming what',
        '# counts as a capability centre stays a human judgement.',
        '',
        'sampled:',
        '  records: %d' % stats['records'],
        '  confirmed_gcc: %d' % stats['confirmed_gcc'],
        '  rest: %d' % stats['rest'],
        '',
    ]
    lines[7] = lines[7] % MIN_LIFT
    lines[9] = lines[9] % MIN_COOCCURRENCE
    lines[13] = lines[13] % MIN_SUPPORT

    lines.append('candidates:')
    if not candidates:
        lines.append('  []  # none cleared both gates')
    for c in candidates:
        lines.append('  - term: "%s"' % c['term'])
        lines.append('    facet: %s' % c['facet'])
        lines.append('    proposed_weight: %d' % c['weight'])
        lines.append('    lift: %.2f' % c['lift'])
        lines.append('    cooccurrence: %.2f' % c['cooccurrence'])
        lines.append('    support: %d' % c['support'])
        lines.append('    samples:')
        for s in c['samples']:
            lines.append('      - "%s"' % s.replace('"', "'")[:110])
    lines.append('')
    lines.append('# Live keywords the corpus no longer supports. Same test run')
    lines.append('# backwards -- this is the automated form of the review that')
    lines.append('# caught "noida" by hand.')
    lines.append('demotion_candidates:')
    if not flagged:
        lines.append('  []  # every live keyword still discriminates')
    for f in flagged:
        lines.append('  - term: "%s"   # lift %.2f, %d in GCC vs %d elsewhere'
                     % (f['term'], f['lift'], f['in_gcc'], f['in_rest']))
    CANDIDATES.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    logger.info('Wrote %s', CANDIDATES)


def main(record=False, write=False):
    store = record_path(str(ROOT))
    Path(store).parent.mkdir(exist_ok=True)

    if record:
        articles = get_articles(force_refresh=False)
        added = record_day(articles, store, get_cache_date(), classify_article)
        logger.info('Recorded %d new articles from the %s cache.',
                    added, get_cache_date() or 'undated')

    records = load_history(store)
    candidates, stats = mine(records)
    flagged = demotions(records)

    logger.info('')
    logger.info('History: %d articles, %d confirmed GCC, %d rest.',
                stats['records'], stats['confirmed_gcc'], stats['rest'])

    if not stats['ready']:
        need = MIN_SUPPORT - stats['confirmed_gcc']
        logger.info('')
        logger.info('Not enough confirmed GCC stories to mine yet: %d of %d.',
                    stats['confirmed_gcc'], MIN_SUPPORT)
        logger.info('Lift computed on a smaller pool would rank one headline\'s')
        logger.info('vocabulary as though it were a pattern, which is the kind')
        logger.info('of number someone acts on. Keep running --record daily;')
        logger.info('roughly %d more qualifying stories to go.', max(need, 0))
        return

    logger.info('%d candidate(s) cleared both gates.', len(candidates))
    logger.info('')
    logger.info('  %-26s %6s %6s %6s %5s  %s',
                'term', 'lift', 'cooc', 'supp', 'wt', 'facet')
    for c in candidates[:25]:
        logger.info('  %-26s %6.2f %6.2f %6d %5d  %s',
                    c['term'][:26], c['lift'], c['cooccurrence'],
                    c['support'], c['weight'], c['facet'])
    if flagged:
        logger.info('')
        logger.info('Demotion candidates (live keywords losing discrimination):')
        for f in flagged:
            logger.info('  %-26s lift %.2f  (%d in GCC vs %d elsewhere)',
                        f['term'][:26], f['lift'], f['in_gcc'], f['in_rest'])

    if write:
        _write_candidates(candidates, stats, flagged)


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--record', action='store_true',
                   help="append today's classified corpus to the history store")
    p.add_argument('--write', action='store_true',
                   help='write config/gcc_candidates.yaml (proposals only)')
    main(**vars(p.parse_args()))
